FROM node:20-bookworm-slim

ARG VITE_PUBLIC_VERSION
ENV VITE_PUBLIC_VERSION=${VITE_PUBLIC_VERSION}
ENV NODE_ENV=production

RUN apt-get update && apt-get install -y --no-install-recommends \
    bash \
    ca-certificates \
    nginx \
    python3 \
    python3-pip \
    make \
    g++ \
    ca-certificates \
    gnupg \
    libu2f-udev \
    software-properties-common \
    xvfb \
    libglib2.0-0\
    libnss3 \
    libnspr4 \
    libdbus-1-3 \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libx11-6 \
    libxcomposite1 \
    libxdamage1 \
    libxext6 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libxcb1 \
    libxkbcommon0 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
    libatspi2.0-0 \
    xauth \
 && rm -rf /var/lib/apt/lists/*

RUN addgroup --system www \
 && adduser --system --ingroup www --home /www --shell /usr/sbin/nologin www \
 && mkdir -p /www \
 && chown -R www:www /www /var/lib/nginx

RUN npm --no-update-notifier --no-fund -g install pnpm@10.6.1 pm2

WORKDIR /usr/src/app
COPY . /usr/src/app
COPY var/docker/nginx.conf /etc/nginx/nginx.conf
RUN pnpm install --frozen-lockfile
RUN pnpx patchright@1.50.0 install chromium
RUN NODE_OPTIONS="--max-old-space-size=4096" pnpm run build

CMD ["bash", "-lc", "nginx && pnpm run pm2"]